version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to DockerHub...
      - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
  build:
    commands:
      - echo Build started on `date`
      - echo Building Docker image...
      - docker build -t $DOCKERHUB_USERNAME/devops-lab:latest .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing Docker image to DockerHub...
      - docker push $DOCKERHUB_USERNAME/devops-lab:latest

artifacts:
  files:
    - '**/*'
